### ISSUE TITLE
No error message from OJS but data does not arrive at DNB

### ISSUE THREAD

**Issue by GrazingScientist** [ojsde/dnb#11]
I just installed the plugin for my OJS 3.1.2 journal ([DNB-Plugin Release 1.3.2](https://github.com/ojsde/dnb/releases/tag/v1.3.2)).

I put in my DNB account data into the form and sent 3 articles for testing purposes to the DNB. OJS showed me a nice green success message. However, the lady from the DNB told me that my hotfolder is empty.

I checked that `tar` is configured and that curl is installed on my system. So, how can I debug the problem?

I appreciate any help! :)

Cheers,

Adrian

**Comment by GrazingScientist** [comment]
Interestingly, I observe the same behavior, when I give wrong credentials (all "test").

**Comment by ronste** [comment]
Hi Adrian,

do you use a proxy configuration? Some proxies return a 200 OK status (because they only report on the connection to the proxy server) even if the connection to the destination host was not successful.

As a general debug procedure please try:
1) Export the tar file an verify the package is ok.
2) Try to connect to the DNB Hotfolder from the command line of the server via sftp <your folder>@hotfolder.dnb.de -p22122.

Best wishes,
Ronald

**Comment by ronste** [comment]
Sorry, the command should read: sftp -P 22122 @hotfolder.dnb.de
