### ISSUE TITLE
SFTP upload failed, connection refused

### ISSUE THREAD

**Issue by TobiasWantzen** [ojsde/dnb#15]
Dear @ronste ,

We are currently running DNB plugin v1.4.1 (2021-08-16) on OJS 3.2.1.1 and we moved to a new hosting provider and got in trouble with the DNB plugin. When trying to transfer an article, I'm instantly getting this notification:
<img width="306" alt="Bildschirmfoto 2022-03-16 um 08 15 35" src="https://user-images.githubusercontent.com/7114561/158536910-511e37ea-655d-4224-a289-3f45c243d776.png">

Since SFTP is running correctly with Portico plugin on the same system, this should be something specially connected to DNB plugin. 

What can we do?

Thanks for your time,
Tobias

PS. When will OJS 3.3.x be supported by DNB plugin?

**Comment by ronste** [comment]
Hi @TobiasWantzen ,

this message indicates that the server tried to connect to hotfolder.dnb.de but the DNB server refused the connection, i.e. the DNB server actually received the request and responded to it. Most commonly this indicates a problem with the access credentials or configuration of the SFTP package on the server.

Please try to connect from your OJS server to the DNB server from the command line like this:

sftp -P 22122 \<username\>@hotfolder.dnb.de:\<folder ID\>

and see if this works. In other cases users had issues with their SFTP configuration disregarding the port parameter and still trying to connect to port 22 instead of 22122.

If this is the case you have to talk to your system administrator/provider to adjust the configuration.

Best wishes,
Ronald

**Comment by ronste** [comment]
Ahh, and the DNB-Plugin 1.5 for OJS 3.3 currently is in the final stages of testing with the DNB. I hope to be able to publish a release soon.

**Comment by TobiasWantzen** [comment]
Thanks, @ronste for your kind answers! We cleared everything with our hosting partner, and now the SFTP transfer works perfectly.
