### ISSUE TITLE
Compatibility with OJS 3.4.x

### ISSUE THREAD

**Issue by testman57** [ojsde/dnb#18]
Hello,
We were trying to upgrade our instance of OJS, but we found out that the DNB plugin does not seem to work.
Do you plan to support OJS 3.4.x in the near future ? 
For reference, it looks like they changed plenty in this version: https://docs.pkp.sfu.ca/dev/release-notebooks/en/3.4-release-notebook
Thanks,

**Comment by ronste** [comment]
Hi @testman57 ,

there definitely will be an update for OJS 3.4 for the DNB Export Plugin. The reason why I didn't start with it yet is because I don't have an active 3.4 journal in production state to do test deliveries to the DNB.

If you could help with running these test delivieries we could provide a 3.4 version reletively soon. Let me know or contact me directly at FU Berlin.

Cheers,
Ronald

**Comment by piccolodream** [comment]
Dear Ronald,

Thanks for the prompt reply. 

We could run the test deliveries if we have a working/compatible version of the plugin.
As soon as you have a compatible version of the plugin, we will upgrade our production instance and run the tests there.
Do you have any alpha-release?

Regards

**Comment by ronste** [comment]
I'm currently working on the upgrade. I would guess I'll have a new version next week. I found your journal and will bring you in contact (via your technical mail address) with the DNB as soon as we are ready for testing.

**Comment by TobiasWantzen** [comment]
@ronste Any news about this topic? We had to upgrade to 3.4.0.4 and now we're missing the DNB plugin.

**Comment by ronste** [comment]
We are more or less through the tests with the DNB. I am waiting for the final approval before I publish a release package. Shouldn't take long.
