### ISSUE TITLE
Add a "Exclude/Do not deposit" option (Feature request)

### ISSUE THREAD

**Issue by aguen** [ojsde/dnb#7]
There are circumstances, where not all published articles can/should be submitted (e.g., articles without PDF, articles transfered from previous publisher). To exclude these articles from automatic or manual upload to DNB, an exclude option would be helpful.

**Comment by TobiasWantzen** [comment]
I second this feature request! There should be an option to exclude articles, but this should be a reversable option! This should mean: If an article is excluded, but should be transfered later, it should be possible to simply uncheck the exclude option and with the next cron run it will be delivered.

**Comment by ronste** [comment]
Hi @aguen , @TobiasWantzen ,

I could certainly implement such a feature. However, I don't fully understand your use cases.

@aguen The plugin will only deposit articles with pdf and epub galleys since only those are accepted by the DNB. Articles without such galleys need not be excluded.

@TobiasWantzen Only published articles will be deposited and those should be ready for delivery to the DNB. Why would you excluded those?

Could you both please detail a little more the uses cases you have in mind?

Best wishes,
Ronald

**Comment by aguen** [comment]
Hi Ronald,

here is one szenario: We publish a journals which was formerly published by a  non-German publisher. The old volumes were transfered to our OJS. Thus these "old" volumes are not subject to the German "Ablieferungspflicht" (I think) as they were not published in Germany. However, I want to use the "automatical submission" option of the DNB plugin for this journals too - but exclude the old volumes. 

Another szenario: I know that some journals use a special issue for advanced online versions of their articles. The final version is than published in a regular issue. I guess it does not make sense to transfer the advanced online versions to DNB.

Best wishes

Armin

**Comment by TobiasWantzen** [comment]
@ronste we are integrating a new journal, which was formerly published under another publisher. For completeness sake, we will integrate (import) the complete archive, but do not need to deliver to DNB, only the actual issues.

Kind regards
Tobias

**Comment by ronste** [comment]
Hi @TobiasWantzen , @aguen ,

I will implement this feature for the plugin version of OJS 3.3 which hopefully will be published soon.

Best wishes,
Ronald

**Comment by ronste** [comment]
Will be included in plugin version 1.5 for OJS 3.3 which wil soon be released.
